//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiraffeSpotter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Reserve
    {
        public Game_Reserve()
        {
            this.Giraffes = new HashSet<Giraffe>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string Category { get; set; }
        public string Username { get; set; }
        public string Status { get; set; }
    
        public virtual Locations Location { get; set; }
        public virtual ICollection<Giraffe> Giraffes { get; set; }
    }
}
