//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiraffeSpotter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GCF_ModelsContainer : DbContext
    {
        public GCF_ModelsContainer()
            : base("name=GCF_ModelsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Profile_Pictures> Profile_Pictures { get; set; }
        public DbSet<Game_Reserve> Game_Reserve { get; set; }
        public DbSet<Giraffe> Giraffes { get; set; }
        public DbSet<Locations> Locations { get; set; }
        public DbSet<Gallery> Galleries { get; set; }
        public DbSet<Observation> Observations { get; set; }
    }
}
