//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiraffeSpotter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giraffe
    {
        public int Id { get; set; }
        public System.DateTime Date_of_Recieval { get; set; }
        public string Sub_Species { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string Place_of_Origin { get; set; }
        public string Status { get; set; }
        public int Game_ReserveId { get; set; }
    
        public virtual Game_Reserve Game_Reserve { get; set; }
    }
}
