//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiraffeSpotter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observation
    {
        public Observation()
        {
            this.Galleries = new HashSet<Gallery>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date_of_Observation { get; set; }
        public string Sub_Species { get; set; }
        public int No_of_Male { get; set; }
        public int No_of_Female { get; set; }
        public int Group_Size { get; set; }
        public System.DateTime Date_of_Submission { get; set; }
        public string Status { get; set; }
        public string Username { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Gallery> Galleries { get; set; }
        public virtual Locations Location { get; set; }
    }
}
